### PR TITLE
revert: remove include external

### PR DESCRIPTION
**Pull request by chriscasto**
# Pull Request Template

## Issue Overview

- [X] This change addresses the issue in full
- [ ] This change addresses only certain aspects of the issue
- [ ] This change is a dependency for another issue
- [ ] This change has a dependency from another issue

## Description

The `includeExternal` endpoint is not being used, so to clean up the code, speed up build/test times, and reduce confusion after handoff, this PR removes it and all accompanying tests and env vars.  This is a removal-only PR; no other code is changed or added.

## How Can This Be Tested/Reviewed?

Run `yarn test` and `yarn test:e2e:local` in the `backend/core` directory as usual.  You can also run `yarn test:unit` under the `sites/public` and `sites/partners` directories.

## Checklist:

- [X] My code follows the style guidelines of this project
- [ ] I have added QA notes to the issue with applicable URLs
- [X] I have performed a self-review of my own code
- [X] I have reviewed the changes in a desktop view
- [ ] I have reviewed the changes in a mobile view
- [ ] I have commented my code, particularly in hard-to-understand areas
- [ ] I have made corresponding changes to the documentation
- [X] My changes generate no new warnings
- [ ] I have added tests that prove my fix is effective or that my feature works
- [X] New and existing unit tests pass locally with my changes
- [ ] Any dependent changes have been merged and published in downstream modules
- [X] I have assigned reviewers
- [X] I have run `yarn generate:client` and/or created a migration if I made backend changes that require them
- [ ] My commit message(s) is/are polished, and any breaking changes are indicated in the message and are well-described
- [ ] Commits made across packages purposefully have the same commit message/version change, else are separated into different commits

## Reviewer Notes:

Steps to review a PR:

- Read and understand the issue, and ensure the author has added QA notes
- Review the code itself from a style point of view
- Pull the changes down locally and test that the acceptance criteria is met
- Also review the acceptance criteria on the Netlify deploy preview (noting that these do not yet include any backend changes made in the PR)
- Either explicitly ask a clarifying question, request changes, or approve the PR if there are small remaining changes but the PR is otherwise good to go

## On Merge:

If you have one commit and message, squash. If you need each message to be applied, rebase and merge.

### CODE REVIEW

**Comment by isaac-looker** [comment]
I'm getting an error loading the site. I see this branch has conflicts so maybe that's part of it. 
Screenshot from 2023-05-31 17-00-30

**Comment by chriscasto** [comment]
@isaac-looker I think that's just because it was based on an older version of main.  I didn't touch any frontend stuff, so it shouldn't cause any issues with React components.  I just merged the latest version of main in, so hopefully that should make that issue go away.

**Comment by phattya** [comment]
Chris, when I `yarn build` in `public` I get the following error. I'm guessing that's from the merge w/main that now has the multiple images from the Bloom merge???
image

image


Thoughts?

**Review by phattya — APPROVED** [review]
Chris, lgtm.  If we don't mind waiting before we merge, I'd prefer Liann review since she's the one that wrote this. Thanks!

yarn test in `backend/core`
image

e2e tests in `backend/core`
image

tests in `sites/public`
image

tests in `sites/partners`
image

**Comment by chriscasto** [comment]
> Chris, when I `yarn build` in `public` I get the following error. I'm guessing that's from the merge w/main that now has the multiple images from the Bloom merge???

I think you're right. I get the same results when I run `yarn build` in main.

**Review by lisunshiny — APPROVED** [review]
(did not read code, but assume that it is fine)

**Pull request merged**
