### PR TITLE
Add filter data to external listings in listing import

### PR DESCRIPTION
**Pull request by chriscasto**
# Pull Request Template

## Issue Overview

- [X] This change addresses the issue in full
- [ ] This change addresses only certain aspects of the issue
- [ ] This change is a dependency for another issue
- [ ] This change has a dependency from another issue

## Description

This PR updates the listings import task to include derived values for filter fields added in #110.  It also adds a new env var, `LISTING_VIEW`, to provide control over what data is pulled in.  This is mainly just a temporary fix to address the fact that some unit fields that are needed for filtering are missing on the base view.

## How Can This Be Tested/Reviewed?

You will need to have a copy of the database from PR #110 in order for the import to work, but if you do, you can run `yarn import:run` as normal then check the values in the `external_listings` table or `combined_listings` view.

Otherwise, `yarn test` works fine for verifying that things work as expected.

## Checklist:

- [X] My code follows the style guidelines of this project
- [ ] I have added QA notes to the issue with applicable URLs
- [X] I have performed a self-review of my own code
- [ ] I have reviewed the changes in a desktop view
- [ ] I have reviewed the changes in a mobile view
- [X] I have commented my code, particularly in hard-to-understand areas
- [ ] I have made corresponding changes to the documentation
- [X] My changes generate no new warnings
- [X] I have added tests that prove my fix is effective or that my feature works
- [X] New and existing unit tests pass locally with my changes
- [ ] Any dependent changes have been merged and published in downstream modules
- [X] I have assigned reviewers
- [ ] I have run `yarn generate:client` and/or created a migration if I made backend changes that require them
- [X] My commit message(s) is/are polished, and any breaking changes are indicated in the message and are well-described
- [ ] Commits made across packages purposefully have the same commit message/version change, else are separated into different commits

## Reviewer Notes:

Steps to review a PR:

- Read and understand the issue, and ensure the author has added QA notes
- Review the code itself from a style point of view
- Pull the changes down locally and test that the acceptance criteria is met
- Also review the acceptance criteria on the Netlify deploy preview (noting that these do not yet include any backend changes made in the PR)
- Either explicitly ask a clarifying question, request changes, or approve the PR if there are small remaining changes but the PR is otherwise good to go

## On Merge:

If you have one commit and message, squash. If you need each message to be applied, rebase and merge.

### CODE REVIEW

**Comment by chriscasto** [comment]
I'm not 100% sure whether `0` if the best default value for "max".  Would using an arbitrarily high value be better?  If so, what's a reasonable value?  99999?  Most filters are based on `>=` on minimum values and I can't imaging a scenario where we would only want something lower than a max value (rent uses min and max, so the min part will always exclude results if there aren't any valid values), but I'm interested in thoughts.

**Comment by chriscasto** [comment]
> I'm not 100% sure whether `0` if the best default value for "max".

Actually, it turns out it probably is.  The search logic for, say, number of bedrooms basically boils down to "find listings where the max number of bedrooms available is greater than the number I'm searching for".  An arbitrarily high value would always return a result, while `0` will exclude listings that don't have any units, which is the behavior we want.  Still open to discussion though.

**Review by phattya — APPROVED** [review]
Lgtm!

**Review by lisunshiny — APPROVED** [review]
FYI I did not review this code, but stamping to unblock merge

**Pull request merged**
