### PR TITLE
Release: pull over changes from core

### PR DESCRIPTION
**Pull request by ludtkemorgan**
Pulls the following changes over from core:

* d54b9a67f -  feat: 3909/add redirect url prisma (#3938)  <cade-exygy>
* dfd580c35 - feat: security patch (#3946)  <Yazeed Loonat>
* ef713505f - fix: limit requestedChangesUser in Listings response (#3921) <Yazeed Loonat>
* 42d56e03c - fix: underscores in translations (#3925) <Emily Jablonski>
* 71d707e38 - refactor: uptake and merge card (#3922)  <Emily Jablonski>
* fc8ac39ed - chore(deps): bump ip from 1.1.5 to 1.1.9 (#3895)  <dependabot[bot]>
* e492219e7 - fix: include demographics in partners applicant csv export  (#3933)  <Krzysztof Zięcina>

Note: There was a lot of merge conflicts around the styling and the card uptake. It would be helpful if someone familiar with these changes to review this PR

### CODE REVIEW

**Comment by emilyjablonski** [comment]
Taking a look but it looks like we lost some of the Doorway styling on the cards

**Comment by emilyjablonski** [comment]
Fixes are here, targeting this branch: https://github.com/metrotranscom/doorway/pull/528

**Comment by cade-exygy** [comment]
Non blocking small style: Cancel should on same line as Submit button
Screenshot 2024-03-14 at 4 27 57 PM

**Comment by YazeedLoonat** [comment]
Hey @ludtkemorgan  I think we'll wanna bring: https://github.com/bloom-housing/bloom/pull/3949

over as well!

**Review by YazeedLoonat — APPROVED** [review]
LGTM

**Pull request merged**
