### PR TITLE
fix: release - seed data and account profile saving issues

### PR DESCRIPTION
**Pull request by emilyjablonski**
Pulls over the following commits from core:
https://github.com/bloom-housing/bloom/pull/4099
https://github.com/bloom-housing/bloom/pull/4121

### CODE REVIEW

**Comment by ColinBuyck** [comment]
I was able to test the 4121 portion of this release and that looks good! But running yarn setup:dev is running into an existing issue on Doorway where it errors on trying to parse Bay Area as the jurisdiction so I was unable to test 4099
Screenshot 2024-06-13 at 4 26 17 PM

**Comment by emilyjablonski** [comment]
Some of the new added parts in the seeds are used in the vanilla `setup`, but that makes sense! I think resolving that might be a separate task.

**Comment by ludtkemorgan** [comment]
I am running into an issue trying to test this. I go to the public site and create an account using my email. Rather than getting the initial account email I am getting the verification code email. I had to try to login and click the "resend email" button to get it to work. Is this something you are seeing?

**Review by ludtkemorgan — APPROVED** [review]
This change looks good. I'm guessing the issue I found is not related to this change but we will want to get that fixed before the release today

**Pull request merged**
