### PR TITLE
Release/2023 05 18

### PR DESCRIPTION
**Pull request by ludtkemorgan**
Pulls in the following features from core:
- Listing export on partners
- Multiple photos

Also includes a few bug fixes

Notes:
- Ran into a decent amount of merge conflicts for the photo upload as expected since Cloudinary is now not the only option. I think I worked through all of the scenarios but I do have the following notes:
  - On both public and partners the calls to `process.env.CLOUDINARY_CLOUD_NAME` were returning null. It worked when I switched it to `process.env.cloudinaryCloudName` but was required to re-add that value to next.config.js for public. It was recently removed and don't know if this will cause issues by re-adding it. Are there any concerns with this approach? @ifranch @chriscasto I believe both of you touched this area.
  - I don't know how to test this with a file service besides cloudinary. Is that something that could be easily tested locally?

### CODE REVIEW

**Comment by chriscasto** [comment]
> * On both public and partners the calls to `process.env.CLOUDINARY_CLOUD_NAME` were returning null. It worked when I switched it to `process.env.cloudinaryCloudName` but was required to re-add that value to next.config.js for public. It was recently removed and don't know if this will cause issues by re-adding it. Are there any concerns with this approach? @ifranch @chriscasto I believe both of you touched this area.

There shouldn't be any problems re-adding it, but we will be taking it out again in the near future (see below).

> * I don't know how to test this with a file service besides cloudinary. Is that something that could be easily tested locally?

We're moving the file upload logic to the backend.  The public and backend sites have already been updated, but the partner site is a WIP.  All the frontend needs to do is send assets to the backend, then the backend will decide where to put them.  All Cloudinary-specific functions and vars will be removed from the frontend to simplify things and minimize confusion.

https://github.com/metrotranscom/doorway/blob/ef5953c17eb8ae5fcde9b5fdb22c047e5f1176d7/backend/core/src/assets/services/assets.service.ts#L29
https://github.com/metrotranscom/doorway/tree/main/backend/core/src/shared/uploads

**Comment by chriscasto** [comment]
> * On both public and partners the calls to `process.env.CLOUDINARY_CLOUD_NAME` were returning null. It worked when I switched it to `process.env.cloudinaryCloudName` but was required to re-add that value to next.config.js for public.

@ludtkemorgan Actually, if this has to do with [this function](https://github.com/metrotranscom/doorway/blob/ef5953c17eb8ae5fcde9b5fdb22c047e5f1176d7/shared-helpers/src/utilities/photos.ts#L33), be advised that there is a PR that already addresses the issue that should be merged soon.  If this fixes what you're seeing, it would be preferred not to add that var back in again.

**Comment by ludtkemorgan** [comment]
> > * On both public and partners the calls to `process.env.CLOUDINARY_CLOUD_NAME` were returning null. It worked when I switched it to `process.env.cloudinaryCloudName` but was required to re-add that value to next.config.js for public.
> 
> @ludtkemorgan Actually, if this has to do with [this function](https://github.com/metrotranscom/doorway/blob/ef5953c17eb8ae5fcde9b5fdb22c047e5f1176d7/shared-helpers/src/utilities/photos.ts#L33), be advised that there is a PR that already addresses the issue that should be merged soon. If this fixes what you're seeing, it would be preferred not to add that var back in again.

That is the function that I needed to update. Awesome. I'll pull that change in when it is merged. Also good to know about the upcoming backend change for upload!

**Comment by chriscasto** [comment]
Great!  Here's the commit with the update: https://github.com/metrotranscom/doorway/pull/112/commits/a30c719b655ddad1c5b49cee1de99b4d0f32d929

It's worth noting that I'm using "exygy" as the default value here because from Doorway's perspective, that's the only value that should be necessary.  All local listings will provide the full URL for assets, so the only time we should need to generate a URL is for listings being fetched from the current Bay Area Bloom instance, which (AFAIK) only ever use Cloudinary and only with "exygy" as the cloud name.  Let me know if see any issues with that logic

**Comment by chriscasto** [comment]
@ludtkemorgan It just got merged https://github.com/metrotranscom/doorway/pull/112

**Comment by ludtkemorgan** [comment]
Thanks @chriscasto I pulled in the latest doorway changes and it worked great! I don't see any issues with "exygy" being the fallback for now

**Review by chriscasto — APPROVED** [review]
Code looks good and all unit/e2e test pass

**Review by lisunshiny — APPROVED** [review]

**Comment by phattya** [comment]
@chriscasto do you want to merge this in? For the conflict, we want to use the `Santa Clara` with the space in it.

**Pull request merged**
