### PR TITLE
feat: add command to reseed with external listings

### PR DESCRIPTION
**Pull request by chriscasto**
# Pull Request Template

## Issue Overview

- [X] This change addresses the issue in full
- [ ] This change addresses only certain aspects of the issue
- [ ] This change is a dependency for another issue
- [ ] This change has a dependency from another issue

## Description

This PR adds two new reseed options, `yarn db:reseed:with-external:dev` and `yarn db:reseed:with-external:prod`, and a couple of supporting actions in the `package.json` file for `backend/core`.  The regular `yarn db:reseed` will now emit a notice if called directly, informing the user that they probably want to use one of the two new options instead.

## How Can This Be Tested/Reviewed?

Run `yarn db:reseed:print-notice` to view the notice that gets displayed when run.
Run `yarn db:reseed` to verify that the notice displays when run.
Run `yarn db:reseed:with-external:prod` to verify that listings are imported from the prod Bloom endpoint and that no notice is displayed.
Run `yarn db:reseed:with-external:dev` to verify that listings are imported from the dev Bloom endpoint and that no notice is displayed.

## Checklist:

- [X] My code follows the style guidelines of this project
- [ ] I have added QA notes to the issue with applicable URLs
- [X] I have performed a self-review of my own code
- [ ] I have reviewed the changes in a desktop view
- [ ] I have reviewed the changes in a mobile view
- [ ] I have commented my code, particularly in hard-to-understand areas
- [ ] I have made corresponding changes to the documentation
- [ ] My changes generate no new warnings
- [ ] I have added tests that prove my fix is effective or that my feature works
- [X] New and existing unit tests pass locally with my changes
- [ ] Any dependent changes have been merged and published in downstream modules
- [X] I have assigned reviewers
- [ ] I have run `yarn generate:client` and/or created a migration if I made backend changes that require them
- [X] My commit message(s) is/are polished, and any breaking changes are indicated in the message and are well-described
- [ ] Commits made across packages purposefully have the same commit message/version change, else are separated into different commits

## Reviewer Notes:

Steps to review a PR:

- Read and understand the issue, and ensure the author has added QA notes
- Review the code itself from a style point of view
- Pull the changes down locally and test that the acceptance criteria is met
- Also review the acceptance criteria on the Netlify deploy preview (noting that these do not yet include any backend changes made in the PR)
- Either explicitly ask a clarifying question, request changes, or approve the PR if there are small remaining changes but the PR is otherwise good to go

## On Merge:

If you have one commit and message, squash. If you need each message to be applied, rebase and merge.

### CODE REVIEW

**Comment by lisunshiny** [comment]
hey! the command works, but there's an error when I try to view on the public site. I think this has to do with uploads being broken or an implicit dependency on env variables here (and the urls seem malformed -- too many slashes)


image

**Comment by lisunshiny** [comment]
at the least we should add some documentation here, the web of env variable dependencies is very tough to figure out.

**Review by lisunshiny — CHANGES_REQUESTED** [review]
see other comments

**Review by isaac-looker — APPROVED** [review]
not a blocker but I recommend putting any bash logic in a script folder like `bin` and invoking from yarn commands, rather than embedding it within the yarn invocations directly.

**Comment by chriscasto** [comment]
> hey! the command works, but there's an error when I try to view on the public site. I think this has to do with uploads being broken or an implicit dependency on env variables here (and the urls seem malformed -- too many slashes)

Can you explain why you think that would be due to this PR?  It doesn't touch any code, all it does is combine a couple of yarn commands together.  None of the seed data uses cloudinary and the listings import doesn't touch image URLs.  Or was this meant for another PR?

**Comment by isaac-looker** [comment]
I recommend creating an issue(s) for any outstanding questions/missing pieces around this feature. This PR is unrelated to the implementation details of showing external listings but allows us to seed from the CD pipeline.

**Comment by lisunshiny** [comment]
Oh fair, the cloudinary stuff is not working properly even on main (all external listing photos seem broken). I still can't see external listings after reseeding, but it works if I switch off of this branch. Let's submit to unblock and then perhaps we can do a bit of a bug bash on the broken things and fix either by documenting how to set up folks' envs or via bugfixes.

**Review by lisunshiny — APPROVED** [review]

**Pull request merged**
