### PR TITLE
fix: if programs is null no longer errors (#4362)

### PR DESCRIPTION
**Pull request by YazeedLoonat**
Releases https://github.com/bloom-housing/bloom/pull/4362

### CODE REVIEW

**Comment by emilyjablonski** [comment]
Curious why the testing file structure changes are different here than they were in core?

**Comment by YazeedLoonat** [comment]
@emilyjablonski ah you caught me red handed lol. The new test for the custom exception filter is most similar to a unit test in terms of how granular we are testing just that file's functionality. But in order to actually test it in the way nestjs uses those exception filters requires an e2e style instantiation of the test nestjs app 

I had originally put it under the unit test folder and named it as if it was a unit test, but because of that instantiation it needs the db present. Everywhere else thats fine, but in doorway when unit tests run the db isn't present. So I had to move the test into the integration test folder and renamed it to be an e2e test 

I was gonna sneak a lil pr into core and then hba to move it in the same way

**Comment by emilyjablonski** [comment]
Sorry for the additional q! Is this waiting on that core PR?

**Comment by YazeedLoonat** [comment]
Hey @emilyjablonski I fixed that in a different PR into main and that'll get merged into doorway sorta completing the circuit 
so I think this is ready whenever you get a chance

**Review by emilyjablonski — APPROVED** [review]
🦤

**Pull request merged**
