### PR TITLE
3/create dockerfiles

### PR DESCRIPTION
**Pull request by chriscasto**
This PR adds 2 dockerfiles: one for the backend service and another for both the public and partner sites, since they should both require the same build steps.  The generic site dockerfile takes a single arg, `SITE`, that is used to determine which one to load at build time.  This _could_ be separated out into two separate files, if needed, but it was easier to iterate on the one and they should, in theory, be identical anyway.

## Commands
Commands below assume you aren't running as a member of the docker group.  If you are a member of that group, you can remove the `sudo`.  All commands should be run from the repo root.  The run commands will run the docker container in the foreground, which is good for viewing output.  If you want to run it in the background, add the `-d` flag to the `docker run` command.

### Backend
**Build:** `sudo docker build --file build/docker/Dockerfile.backend --target run -t doorway/backend:run ./backend/core`
**Run:** `sudo docker run -p 3100:3100 doorway/backend:run`

### Public Site
**Build:** `sudo docker build --file build/docker/Dockerfile.sites-generic --build-arg "SITE=public" --target run -t doorway/public:run .`
**Run:** `sudo docker run -p 3000:3000 doorway/public:run`

### Partner Site
**Build:** `sudo docker build --file build/docker/Dockerfile.sites-generic --build-arg "SITE=partners" --target run -t doorway/partners:run .`
**Run:** `sudo docker run -p 3001:3001 doorway/partners:run`

### CODE REVIEW

**Comment by chriscasto** [comment]
The backend site has not been fully tested, but unit tests pass.  Starting it up generates an error about missing env vars (below), which is to be expected.

```
Error: Config validation error: "PORT" is required. "EMAIL_API_KEY" is required. "DATABASE_URL" is required. "APP_SECRET" is required. "CLOUDINARY_SECRET" is required. "CLOUDINARY_KEY" is required. "PARTNERS_PORTAL_URL" is required
    at Function.forRoot (/app/node_modules/@nestjs/config/dist/config.module.js:78:23)
    at Object.<anonymous> (/app/dist/src/shared/shared.module.js:21:35)
    at Module._compile (internal/modules/cjs/loader.js:1072:14)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1101:10)
    at Module.load (internal/modules/cjs/loader.js:937:32)
    at Function.Module._load (internal/modules/cjs/loader.js:778:12)
    at Module.require (internal/modules/cjs/loader.js:961:19)
    at require (internal/modules/cjs/helpers.js:92:18)
    at Object.<anonymous> (/app/dist/src/auth/auth.module.js:17:25)
    at Module._compile (internal/modules/cjs/loader.js:1072:14)
```

**Comment by chriscasto** [comment]
The public site builds without error and has been verified to run as expected locally.

The partner site builds fine but fails to load with the following error:

```
$ next start -p ${NEXTJS_PORT:-3001}
ready - started server on 0.0.0.0:3001, url: http://localhost:3001
Using http://localhost:3100/listings for the listing service.
Error: Could not find a production build in the '/app/sites/partners/.next' directory. Try building your app with 'next build' before starting the production server. https://nextjs.org/docs/messages/production-start-no-build-id
    at NextNodeServer.getBuildId (/app/node_modules/next/dist/server/next-server.js:169:23)
    at new Server (/app/node_modules/next/dist/server/base-server.js:58:29)
    at new NextNodeServer (/app/node_modules/next/dist/server/next-server.js:70:9)
    at NextServer.createServer (/app/node_modules/next/dist/server/next.js:140:16)
    at async /app/node_modules/next/dist/server/next.js:149:31
error Command failed with exit code 1.
info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.
```

There doesn't appear to be any reason why the expected files would not be present.  The `build` stage runs `yarn build`, which invokes `next build` per the [package.json](https://github.com/metrotranscom/doorway/blob/4034440ccdff2419bfbe7a34bd259dc6b7f1d96c/sites/partners/package.json#L15) file.  The `run` stage pulls in build artifacts from the `build` stage, including `/app/sites/${SITE}/.next`.  This all works as expected for the public site, but fails for some reason with the partner site.  Adding `RUN ls -la ./.next` after the build step verifies that the BUILD_ID file is not present after running `next build` on the partner site.

**Comment by chriscasto** [comment]
Thank you @ludtkemorgan!  I think you saved us a lot of time that would have been mostly spent spinning our wheels.  I'll make those changes and push them out later today.

**Comment by chriscasto** [comment]
Success!  I verified that everything builds successfully with the changes that Morgan suggested.  Thanks again @ludtkemorgan !

@isaac-looker Do you want to try building it yourself or should we just go ahead and merge?

**Review by glgh — APPROVED** [review]

**Comment by isaac-looker** [comment]
I'm fine with merging; thanks! :ship:

**Comment by chriscasto** [comment]
@isaac-looker Can you go ahead and approve? PRs in this repo require two approvals to merge

**Pull request merged**
