### PR TITLE
fix: release - update password requirements (#4107)

### PR DESCRIPTION
**Pull request by emilyjablonski**
Pulls over https://github.com/bloom-housing/bloom/pull/4107 from core

### CODE REVIEW

**Review by mcgarrye — COMMENTED** [review]
Strange behavior happening when I input an invalid or valid password on the public site when creating an account. Causes page to reload and empties all fields

**Comment by emilyjablonski** [comment]
This was fixed! Was a weird rebase issue

**Review by YazeedLoonat — APPROVED** [review]
LGTM

**Comment by YazeedLoonat** [comment]
@mcgarrye I gave it the approval but if you wanna take another peep at what you were running into and give an approval too I didn't change the tag yet

**Review by mcgarrye — APPROVED** [review]
Looks good! LGTM

**Pull request merged**
