### PR TITLE
fix: add db:reseed:ci

### PR DESCRIPTION
**Pull request by chriscasto**
# Pull Request Template

## Issue Overview

- [X] This change addresses the issue in full
- [ ] This change addresses only certain aspects of the issue
- [ ] This change is a dependency for another issue
- [ ] This change has a dependency from another issue

## Description

There's a chicken-and-egg situation that happens with reseeding.  The first thing it does is try to drop the `bloom` table, but if that's the table you're connected to when you run the command, it fails.  This is less an issue in local dev environments where there are alternate databases to use, but in CI environments that isn't necessarily an option and automating around it can be a pain.  This PR adds a new yarn command, `db:reseed:ci`, that addresses this issue by automatically creating a new temporary database and running database reset commands from there before reseeding.

Documentation for this and other commands will be added later, once more important tasks are complete.

## How Can This Be Tested/Reviewed?

Run `yarn db:reseed:ci` and verify that it completes successfully.  You can also verify that the `temp` database is not used for populating seed data by running `psql -d temp -c '\d'`, which should print "Did not find any relations."  If your `bloom` database doesn't yet exist for some reason, you can change the starting database by setting `PGDATABASE` ahead of the command like this: `PGDATABASE=<other_db_name> yarn db:reseed:ci`.

## Checklist:

- [X] My code follows the style guidelines of this project
- [ ] I have added QA notes to the issue with applicable URLs
- [ ] I have performed a self-review of my own code
- [ ] I have reviewed the changes in a desktop view
- [ ] I have reviewed the changes in a mobile view
- [ ] I have commented my code, particularly in hard-to-understand areas
- [ ] I have made corresponding changes to the documentation
- [X] My changes generate no new warnings
- [ ] I have added tests that prove my fix is effective or that my feature works
- [X] New and existing unit tests pass locally with my changes
- [ ] Any dependent changes have been merged and published in downstream modules
- [X] I have assigned reviewers
- [ ] I have run `yarn generate:client` and/or created a migration if I made backend changes that require them
- [ ] My commit message(s) is/are polished, and any breaking changes are indicated in the message and are well-described
- [ ] Commits made across packages purposefully have the same commit message/version change, else are separated into different commits

## Reviewer Notes:

Steps to review a PR:

- Read and understand the issue, and ensure the author has added QA notes
- Review the code itself from a style point of view
- Pull the changes down locally and test that the acceptance criteria is met
- Also review the acceptance criteria on the Netlify deploy preview (noting that these do not yet include any backend changes made in the PR)
- Either explicitly ask a clarifying question, request changes, or approve the PR if there are small remaining changes but the PR is otherwise good to go

## On Merge:

If you have one commit and message, squash. If you need each message to be applied, rebase and merge.

### CODE REVIEW

**Comment by chriscasto** [comment]
@phattya and @ifranch since I think you've both run into this before and are probably best to test this

@isaac-looker FYI

**Comment by isaac-looker** [comment]
https://github.com/metrotranscom/doorway/pull/118/files#diff-f104fe6796ebd48fee62979eeafd05637d4b164d7c526c5c0aaed875b18cbb49R61

**Review by ifranch — APPROVED** [review]
I followed the testing steps and this all worked as expected, thanks for the fix!

**Comment by chriscasto** [comment]
> Another option is to use `template1`

That's a great point!  I'll make that change since it will simplify things a bit

**Review by isaac-looker — APPROVED** [review]

**Review by phattya — APPROVED** [review]
Lgtm. Reseed went as expected ... no issues.

**Pull request merged**
