### PR TITLE
fix: add user and application import scripts

### PR DESCRIPTION
**Pull request by ludtkemorgan**
This PR addresses [#4193](https://github.com/bloom-housing/bloom/issues/4193)

- [x] Addresses the issue in full
- [ ] Addresses only certain aspects of the issue

## Description

Creates a script that does the following two things:
- Pulls over all partner users in HBA tied to at least one listing in the requested jurisdiction. Then ties it to the same listing in Doorway
- Pulls over all public users in HBA that have at least one application submitted in the requested jurisdiction. Then copies over all of those applications to Doorway
  - No PII is carried over for the applications

## How Can This Be Tested/Reviewed?

This requires the previous jurisdiction scripts to be run so the following steps need to be run:
- Do a reseed locally
- Start up the app locally and go to the swagger api http://localhost:3100/api.
- Login via the api to the admin account http://localhost:3100/api#/auth/login.
- Go to Heroku and get the DB credentials for the HBA staging environment https://data.heroku.com/datastores/fd968c98-f208-4066-b8cf-7d3a6bf8ff03#administration
- Use the credentials from above to run the first script http://localhost:3100/api#/scriptRunner/transferJurisdictionData.
- Run the script for http://localhost:3100/api#/scriptRunner/transferJurisdictionListingsData using the same db credentials and jurisdiction used in the previous script
- Run the latest script to migrate users and applications http://localhost:3100/api#/scriptRunner/transferJurisdictionUserApplicationData.
- Verify that the expected partner users from HBA staging have been carried over. You can verify partner users by logging into the partner site and going to the /users tab. Note: you need to be logged in as an admin to see those users. 
- Verify public users have been transferred over. The easiest way is to compare the user_accounts and associated tables in the database 
- Verify that applications have properly been carried over. You can do this by looking at the properties in the partner site and clicking on the applications tab and then the specific application you want to look at.

Notes:
- Testing with SMC will give you data, but there is much more data in HBA staging for Alameda. If you want to test with Alameda you will notice the following:
  - The Alameda jurisdiction isn't in the system so you will need to either manually add it or add it in the seeding script.
  - There will be a lot of logs output in the listing script because the data isn't great and also not every reserved type is carried over. This is ok, we only care about making sure the applications and users are transferred.

## Author Checklist:

- [ ] Added QA notes to the issue with applicable URLs
- [x] Reviewed in a desktop view
- [x] Reviewed in a mobile view
- [x] Reviewed considering accessibility
- [x] Added tests covering the changes
- [ ] Made corresponding changes to the documentation
- [ ] Ran `yarn generate:client` and/or created a migration when required

## Review Process:

- Read and understand the issue
- Ensure the author has added QA notes
- Review the code itself from a style point of view
- Pull the changes down locally and test that the acceptance criteria is met
- Either (1) explicitly ask a clarifying question, (2) request changes, or (3) approve the PR, even if there are very small remaining changes, if you don't need to re-review after the updates

### CODE REVIEW

**Review by YazeedLoonat — APPROVED** [review]
LGTM

**Review by mcgarrye — CHANGES_REQUESTED** [review]
Screenshot 2024-10-08 at 2 36 37 PM
Partner accounts with matching emails causes error to be thrown and script to fail

**Comment by ludtkemorgan** [comment]
@mcgarrye great catch! I pushed up a fix for that. Any partner user that conflicts with an existing user in Doorway is now logged and not added to the db

**Comment by mcgarrye** [comment]
> @mcgarrye great catch! I pushed up a fix for that. Any partner user that conflicts with an existing user in Doorway is now logged and not added to the db

Looks good and doesn't break! Just want to confirm two functional things before I approve.
1. For any partner accounts that already exist in Doorway, should the listing assignments from HBA be added to their existing account? As it stand right now, this does not happen.
2. Should jurisdictional admins for San Mateo be copied over? As it stand right now, this does not happen.

**Comment by ludtkemorgan** [comment]
> Looks good and doesn't break! Just want to confirm two functional things before I approve.
> 
> 1. For any partner accounts that already exist in Doorway, should the listing assignments from HBA be added to their existing account? As it stand right now, this does not happen.
> 2. Should jurisdictional admins for San Mateo be copied over? As it stand right now, this does not happen.

@mcgarrye  Good questions:
1. That is correct. It just logs the user email and the listings. After these scripts are run we will need to manually go through to  see if we should merge them or not. 
2. That is intended. Those are going to get manually created by the SMC team. The permission levels might change per user so we aren't going to automatically move them.

**Review by mcgarrye — APPROVED** [review]
LGTM

**Pull request merged**
