### PR TITLE
feat: programs on listings (#4412)

### PR DESCRIPTION
**Pull request by YazeedLoonat**
Releases https://github.com/bloom-housing/bloom/pull/4412 to hba

**WE NEED TO RUN A SCRIPT RUNNER SCRIPT FOR THIS ONE**

### CODE REVIEW

**Comment by ludtkemorgan** [comment]
@YazeedLoonat this is failing because of this lint error
```
/home/runner/work/doorway/doorway/sites/public/src/components/listing/ListingView.tsx
Warning:   27:31  warning  '/home/runner/work/doorway/doorway/node_modules/@bloom-housing/ui-seeds/index.ts' imported multiple times  import/no-duplicates
Warning:   43:47  warning  '/home/runner/work/doorway/doorway/node_modules/@bloom-housing/ui-seeds/index.ts' imported multiple times  import/no-duplicates
```

**Review by ludtkemorgan — CHANGES_REQUESTED** [review]
The preference section in Doorway is blue instead of white while this new program section is white. Is that intended? if not should the preferences become white or should the programs become blue?
image

**Review by emilyjablonski — APPROVED** [review]
🚰

**Review by ColinBuyck — APPROVED** [review]
🚰

**Review by ludtkemorgan — APPROVED** [review]

**Pull request merged**
