### PR TITLE
feat: release lottery apps fe 2

### PR DESCRIPTION
**Pull request by ColinBuyck**
This PR releases the following commits 

- feat: application side nav https://github.com/bloom-housing/bloom/pull/4237
- feat: feature flag and new endpoint https://github.com/bloom-housing/bloom/pull/4252
- fix: build resolution https://github.com/bloom-housing/bloom/pull/4278
- fix: clean up dto https://github.com/bloom-housing/bloom/pull/4281
- feat: lottery public list view https://github.com/bloom-housing/bloom/pull/4286

## How Can This Be Tested/Reviewed?

This PR can be tested by creating a public user and applying to listings that are open (with and without application due dates), closed (with and without lottery dates), and lottery run (triggered by publishing to public. Ensure the side nav, statues and buttons all show as expected.

UPDATE ON NOTE BELOW: Em pointed me to this [document](https://www.figma.com/design/Owt7RS8r1ESz3XhojupJVh/dwy-seeds?node-id=1-5166&node-type=CANVAS&m=dev) which detailed how to translate the tags on the left to the desired appearance on the right. The most recent commit handles that.

PLEASE NOTE: The variable overrides are creating contrast errors and I am discussing with design on how these should be addressed.

Screenshot 2024-09-06 at 6 49 23 PM

### CODE REVIEW

**Review by emilyjablonski — APPROVED** [review]
🦐

**Comment by emilyjablonski** [comment]
Curious to look into the failing Cypress suites

**Comment by ColinBuyck** [comment]
Looks like merging in main worked @emilyjablonski. Thanks for the review!

**Comment by emilyjablonski** [comment]
@ColinBuyck We may need docker file changes: https://www.notion.so/exygy/How-to-turn-on-a-public-partner-environment-variable-in-AWS-7e592404da8b41b7a3228da4a5415c1b?pvs=4

**Comment by mcgarrye** [comment]
Screenshot 2024-09-11 at 9 56 02 AM
Thissss don't look right

**Comment by emilyjablonski** [comment]
@mcgarrye You'll need to run `yarn install` to pick up the UIC/Seeds changes

**Review by mcgarrye — APPROVED** [review]
LGTM!

**Pull request merged**
