### PR TITLE
fix: listings filtering UI bugs

### PR DESCRIPTION
**Pull request by jaredcwhite**
This PR addresses #505

- [x] Addresses the issue in full
- [ ] Addresses only certain aspects of the issue

## Description

Min and max rental filters couldn't be removed once present…having no value in the field would end up resetting to the previous value after saving the filter. This PR ensures a removed amount will switch off that filter.

## How Can This Be Tested/Reviewed?

Try adding values to min and/or max rent when browsing listings, and then removing them.

## Author Checklist:

- [ ] Added QA notes to the issue with applicable URLs
- [x] Reviewed in a desktop view
- [x] Reviewed in a mobile view
- [x] Reviewed considering accessibility
- [ ] Added tests covering the changes
- [ ] Made corresponding changes to the documentation
- [ ] Ran `yarn generate:client` and/or created a migration when required

## Review Process:

- Read and understand the issue
- Ensure the author has added QA notes
- Review the code itself from a style point of view
- Pull the changes down locally and test that the acceptance criteria is met
- Either (1) explicitly ask a clarifying question, (2) request changes, or (3) approve the PR, even if there are very small remaining changes, if you don't need to re-review after the updates

### CODE REVIEW

**Comment by cade-exygy** [comment]
@jaredcwhite This PR that is ready for review may impact this. I believe the changes in my PR address the referenced issue but we would need to test to make sure: https://github.com/metrotranscom/doorway/pull/571/files

**Comment by jaredcwhite** [comment]
@cade-exygy I think my fix is complementary to the work you've done there…at first glance I don't see anything which changes the behavior around min/max rent specifically.

**Comment by cade-exygy** [comment]
> @cade-exygy I think my fix is complementary to the work you've done there…at first glance I don't see anything which changes the behavior around min/max rent specifically.

Okay sounds good, that makes sense. Just wanted to highlight in case there is something that comes up!

**Review by mcgarrye — COMMENTED** [review]
In practice this is clearing the filter but visually it doesn't clear it while still in the modal

https://github.com/metrotranscom/doorway/assets/46828798/ef9f9f5b-5d0d-4bc5-b726-454f8560a388

**Comment by jaredcwhite** [comment]
@mcgarrye Thanks for catching that! Hadn't even noticed that clear filters link down there to be honest. I'll look into it.

**Review by mcgarrye — APPROVED** [review]
Looks good! Let's wait on merging though bc the last commit to be merge is causing a breaking issue atm

**Comment by mcgarrye** [comment]
breaking change has been fixed! merge as you please

**Pull request merged**
