### PR TITLE
feat: add mtc logo to the top nav, remove from footer

### PR DESCRIPTION
**Pull request by jaredcwhite**
This PR addresses #934 

- [x] Addresses the issue in full
- [ ] Addresses only certain aspects of the issue

## Description

This adds the MTC logo to the left side (or above on mobile) of the languages nav bar.

## How Can This Be Tested/Reviewed?

Visit the Public site and verify the logo is available at the top-left and goes to the right website when clicked, and that the logo has been removed from the footer.

**Note:** in the Figma mockups linked in the issue, the language bar looks different than what's currently in Doorway production. If the code needs to be revised to match Figma's appearance, I'd recommend a follow-up ticket to address that.

**Note 2:** I did "Seeds-ify" the CSS of the language bar, and I would have also moved it out of doorway-ui-components except it's referenced by the SiteHeader component. Happy to discuss options.

## Author Checklist:

- [ ] Added QA notes to the issue with applicable URLs
- [x] Reviewed in a desktop view
- [x] Reviewed in a mobile view
- [ ] Reviewed considering accessibility
- [ ] Added tests covering the changes
- [ ] Made corresponding changes to the documentation
- [ ] Ran `yarn generate:client` and/or created a migration when required

## Review Process:

- Read and understand the issue
- Ensure the author has added QA notes
- Review the code itself from a style point of view
- Pull the changes down locally and test that the acceptance criteria is met
- Either (1) explicitly ask a clarifying question, (2) request changes, or (3) approve the PR, even if there are very small remaining changes, if you don't need to re-review after the updates

### CODE REVIEW

**Comment by ColinBuyck** [comment]
I'm noticing a slight misalignment between the 20px here and the 24px of the "Doorway" below in the siteheader
Screenshot 2024-12-02 at 9 46 31 AM

**Comment by jaredcwhite** [comment]
Ah, I guess there's a mismatch due to the responsive design sizing of the logo.

Here's what it looks like on a larger window size:

image

but then on a medium width, the Doorway logo shrinks but the MTC logo doesn't.

I don't really understand why the Doorway logo is shrinking when it does, there's still plenty of blank space to the right of it. I'll see if I can normalize all of this a bit.

**Comment by jaredcwhite** [comment]
OK, I got the logo to maintain a consistent size across that particular breakpoint ("tablet"). It required a very tiny amount of space shaved off between the nav bar links so the "W" of Welcome doesn't smash up against the logo. Hopefully that's an acceptable tradeoff!

**Comment by jaredcwhite** [comment]
I'm losing my mind, I forgot to commit the changes. Here it is! 😅

**Comment by jaredcwhite** [comment]
hmm, there's now a styles conflict with this and main. I'll look into it

**Review by ColinBuyck — APPROVED** [review]
LGTM 🐐

**Pull request merged**
